/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bugtrackingsystem.modules;

import bugtrackingsystem.forms.Login1;
import bugtrackingsystem.forms.UpdateBugStatus;
import bugtrackingsystem.tables.Bugs;
import bugtrackingsystem.tables.DevPerformance;
import bugtrackingsystem.tables.TesterPerformance;

/**
 *
 * @author zeyad
 */
public class ProjectManager extends javax.swing.JFrame {

    private final String name;
    private final int id;

    public ProjectManager(String name, int id) {
        this.name = name;
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeMsg = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        viewBugs = new javax.swing.JButton();
        devPerform = new javax.swing.JButton();
        testPerform = new javax.swing.JButton();
        updateStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PM Panel");

        welcomeMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomeMsg.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMsg.setText("Welcome "+name);
        welcomeMsg.setPreferredSize(new java.awt.Dimension(250, 32));

        logOutBtn.setBackground(new java.awt.Color(255, 102, 0));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtnMouseClicked(evt);
            }
        });

        viewBugs.setBackground(new java.awt.Color(255, 102, 0));
        viewBugs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewBugs.setForeground(new java.awt.Color(255, 255, 255));
        viewBugs.setText("View All Bugs");
        viewBugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBugsActionPerformed(evt);
            }
        });

        devPerform.setBackground(new java.awt.Color(255, 102, 0));
        devPerform.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        devPerform.setForeground(new java.awt.Color(255, 255, 255));
        devPerform.setText("View Developers Performance");
        devPerform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devPerformActionPerformed(evt);
            }
        });

        testPerform.setBackground(new java.awt.Color(255, 102, 0));
        testPerform.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        testPerform.setForeground(new java.awt.Color(255, 255, 255));
        testPerform.setText("View Testers Performance");
        testPerform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testPerformActionPerformed(evt);
            }
        });

        updateStatus.setBackground(new java.awt.Color(255, 102, 0));
        updateStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateStatus.setForeground(new java.awt.Color(255, 255, 255));
        updateStatus.setText("Update Status");
        updateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(logOutBtn)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewBugs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(devPerform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testPerform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(welcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logOutBtn))
                    .addComponent(jLabel1))
                .addGap(91, 91, 91)
                .addComponent(viewBugs)
                .addGap(18, 18, 18)
                .addComponent(devPerform)
                .addGap(18, 18, 18)
                .addComponent(testPerform)
                .addGap(18, 18, 18)
                .addComponent(updateStatus)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login1().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_logOutBtnMouseClicked

    private void viewBugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBugsActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bugs(id).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_viewBugsActionPerformed

    private void devPerformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devPerformActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevPerformance(id).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_devPerformActionPerformed

    private void testPerformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testPerformActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesterPerformance(id).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_testPerformActionPerformed

    private void updateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpdateBugStatus(name, id).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_updateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devPerform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton testPerform;
    private javax.swing.JButton updateStatus;
    private javax.swing.JButton viewBugs;
    private javax.swing.JLabel welcomeMsg;
    // End of variables declaration//GEN-END:variables
}
